### PR TITLE
Update StringDictionary.zh-Hant.xaml

### PR DESCRIPTION
**Pull request by han880805**

### CODE REVIEW

**Comment by Stanly5** [comment]
@han880805 
Hello~
Thank you so much for your interesting and contribution. I'd like ask you below things. Please kindly give me your advice.
- Proxy : what we checked, in Chinese Windows setting Microsoft is using Proxy as it is, not translated. Is it correct? Basically we'd like to use same words according to the Windows.
- Mostly you suggested to remove "." on existing translation. Could you please advise me which case "." is used, and which case "." is not used.
Thank you and have a great day~

**Comment by han880805** [comment]
1. I translated the "Proxy" to "代理伺服器" because this translation usually appears in the government websites. Many modern browsers such as Firefox also use this translation.
2. This is because we don't use "." as period mark in chinese but use "。". I made some mistake in this operation, I should change the "." to "。" instead.

**Comment by Stanly5** [comment]
@han880805
Thank you so much for your advice.
I'm sorry for bothering you, but please kindly advise me again so that I can learn it.
"。" is necessary for these sentence?
Is there a different meaning with and without "。"?
Is it an error if there isn't "。"? Or not comfortable?

**Comment by han880805** [comment]
The "。" in Chinese represents same meaning of "." in English.
So use the "。" in the end of the sentence is proper.
(But without it doesn't make a different meaning , just makes informality)

**Pull request merged**
