### PR TITLE
Update StringDictionary.pl.xaml

### PR DESCRIPTION
**Pull request by a-w11**
First update of polish translation.

### CODE REVIEW

**Comment by Stanly5** [comment]
@a-w11  Thank you so much for your quick update~

**Comment by Stanly5** [comment]
@a-w11
Please review the updated screen images again.

new setting
new adding sftp
new adding ftp

**Comment by a-w11** [comment]
It's all fine 👍

**Comment by Stanly5** [comment]
Great! Thanks for your contribution again.

**Comment by Stanly5** [comment]
Hello Adrian,
String line for Proxy was added, and I made it tentatively like below.
Could you please review it is ok or not?

<system:String x:Key="Settings.Proxy">Proxy</system:String>

**Comment by a-w11** [comment]
Hello,

Proxy in polish is proxy :-)

**Comment by Stanly5** [comment]
Thank you so much for your quick advice~!

**Comment by Stanly5** [comment]
@a-w11 
Hello Adrian,
RaiDrive 1.4.0 is released. With your great contribution, translated Polish is applied on it and also new file can be tested with it.

**Pull request merged**
