### PR TITLE
Update StringDictionary.de.xaml

### PR DESCRIPTION
**Pull request by Kasukoi**
Should be everything here. Remaining English words like "Login" are commonly used in the German language so there should be no need to change them.

### CODE REVIEW

**Comment by Stanly5** [comment]
@Kasukoi 
Thank you so much for your contribution.
I'd like to share the screen shot for reviewing before release test version of translation, even few screen. If you find something to be improved or changed, then issuing Pull request again would be greatly appreciated.

settings
main
adding sftp
adding ftp

**Comment by Kasukoi** [comment]
When adding a new Drive (Neues Laufwerk), the "Passwort" next to the "Benutzername" seems to be missing. Other than that, everything seems to be fine!

screenshot_53

**Comment by Stanly5** [comment]
String line for Proxy was added, and I made it tentatively like below.
Could you please review it is ok or not?

<system:String x:Key="Settings.Proxy">Proxy</system:String>

**Comment by Stanly5** [comment]
@Kasukoi 
RaiDrive 1.4.0 is released. With your great contribution, translated German is applied on it and also new file can be tested with it.

**Pull request merged**
