### PR TITLE
Translation enhancement

### PR DESCRIPTION
**Pull request by Mugahedb**
Few words updated, testing new rendering for {0} free of {1} {2} in arabic

### CODE REVIEW

**Comment by Stanly5** [comment]
Please review below screenshots which is what I can do right now.
As soon as multilingual beta version is ready to release, I will send you it.

settings
main
adding ftp
adding sftp

**Comment by Mugahedb** [comment]
@Stanly5 
The translation is more accurate now.  For {0} free of {1} {2} , I suggest to leave it in English because rendering is still not as it should be. 
Let us wait for the beta version.

**Comment by Stanly5** [comment]
OK, I will follow your suggestion leaving in English.
Thank you so much for your contribution.

**Comment by Stanly5** [comment]
String line for Proxy was added, and I made it like below.
Could you please review it is ok or not?

<system:String x:Key="Settings.Proxy">مخدم بروكسي</system:String>

**Pull request merged**
