### PR TITLE
All lines translated

### PR DESCRIPTION
**Pull request by kazihorka**
Hi, new version of CZ translation, all lines should be translated now!

### CODE REVIEW

**Comment by Stanly5** [comment]
@kazihorka 
Thank you so much for the completion of translation!

As we mentioned, newly added lines for v.1.7.0 which is line#223 to line#229 are done by translate app, so could you please confirm it is good to understand or not?

**Comment by kazihorka** [comment]
I had a problem with line 228, the English text doesn't make sense for me, so even the Czech will be a little off.

**Comment by Stanly5** [comment]
@kazihorka 
Line# 228 : "Your current session has been requested to return by your other session{0}. All drives will be reconnected. Please save file(s) or close application(s)"
It's for the professional version which is charged subscription version. Subscription is based on session, and session defined active connection. When trying to add more active session which is greater than what you are subscribing, then oldest session will be de-active and above message will be poped up.
For example, if you are subscribe 1 session, and remain activate RaiDrive in your office and then try to activate 1 more session in home, then RaiDrive in office will be de-activate and send a message before shutdown to keep just 1 session you subcribe. Do you think it make sense?

**Comment by kazihorka** [comment]
@Stanly5 
Just my opinion: "Your current session couldn't be executed, because other session is active or connected. Running another session would exceed your subscription's limit. All drives will be reconnected. Please save file(s) or close application(s)"

**Pull request merged**
